import { ANDEAN_CARAVAN_FIRST_DEPARTURE } from "@/content/andean-caravan";
import { assetManifest } from "@/content/assets";
import { TO_BE_CONFIRMED, type Journey } from "@/lib/types";

const placeholderSection = [TO_BE_CONFIRMED] as const;

export const journeys = [
  {
    id: "journey-patagonia-slowly-demo",
    slug: "patagonia-slowly",
    title: "Patagonia, slowly",
    destination: "Aysén",
    country: "Chile",
    startDate: TO_BE_CONFIRMED,
    endDate: TO_BE_CONFIRMED,
    dateLabel: ANDEAN_CARAVAN_FIRST_DEPARTURE,
    durationDays: 8,
    capacity: 6,
    seatsRemaining: 2,
    seatStatusLabel: "2 seats open",
    status: "forming",
    priceLabel: TO_BE_CONFIRMED,
    pace: TO_BE_CONFIRMED,
    archetypes: ["slow-wanderer"],
    fitLabel: "Fits Slow Wanderers",
    heroImage: assetManifest["journey-patagonia-hero"],
    cardImage: assetManifest["journey-patagonia-card"],
    story: placeholderSection,
    dayRhythm: placeholderSection,
    included: placeholderSection,
    held: placeholderSection,
    fieldStatus: {
      dates: "PLACEHOLDER",
      durationDays: "DRAFT",
      capacity: "DRAFT",
      seatsRemaining: "DRAFT",
      priceLabel: "PLACEHOLDER",
      pace: "PLACEHOLDER",
      story: "PLACEHOLDER",
      dayRhythm: "PLACEHOLDER",
      included: "PLACEHOLDER",
      held: "PLACEHOLDER",
      images: "PLACEHOLDER",
    },
    demoOnly: true,
    contentStatus: "DRAFT",
    contentNote:
      "Visual-manual journey specimen only. The month/year, duration, capacity and seat label are draft; exact dates, price, pace, story and operating details are not supplied.",
  },
  {
    id: "journey-carretera-austral-demo",
    slug: "the-carretera-austral",
    title: "The Carretera Austral",
    destination: "Patagonia",
    country: "Chile",
    startDate: TO_BE_CONFIRMED,
    endDate: TO_BE_CONFIRMED,
    dateLabel: TO_BE_CONFIRMED,
    durationDays: 10,
    capacity: 5,
    seatsRemaining: null,
    seatStatusLabel: "Forming",
    status: "forming",
    priceLabel: TO_BE_CONFIRMED,
    pace: TO_BE_CONFIRMED,
    archetypes: ["improviser"],
    fitLabel: "Fits Improvisers",
    heroImage: assetManifest["journey-carretera-hero"],
    cardImage: assetManifest["journey-carretera-card"],
    story: placeholderSection,
    dayRhythm: placeholderSection,
    included: placeholderSection,
    held: placeholderSection,
    fieldStatus: {
      dates: "PLACEHOLDER",
      durationDays: "DRAFT",
      capacity: "DRAFT",
      seatsRemaining: "PLACEHOLDER",
      priceLabel: "PLACEHOLDER",
      pace: "PLACEHOLDER",
      story: "PLACEHOLDER",
      dayRhythm: "PLACEHOLDER",
      included: "PLACEHOLDER",
      held: "PLACEHOLDER",
      images: "PLACEHOLDER",
    },
    demoOnly: true,
    contentStatus: "DRAFT",
    contentNote:
      "Visual-manual journey specimen only. Duration, capacity and forming status are draft; seats, dates, price, pace, story and operating details are not supplied.",
  },
  {
    id: "journey-atacama-stars-demo",
    slug: "atacama-and-the-stars",
    title: "Atacama & the stars",
    destination: "San Pedro",
    country: "Chile",
    startDate: TO_BE_CONFIRMED,
    endDate: TO_BE_CONFIRMED,
    dateLabel: TO_BE_CONFIRMED,
    durationDays: 6,
    capacity: 4,
    seatsRemaining: 1,
    seatStatusLabel: "1 seat open",
    status: "forming",
    priceLabel: TO_BE_CONFIRMED,
    pace: TO_BE_CONFIRMED,
    archetypes: ["night-owl"],
    fitLabel: "Fits Night Owls",
    heroImage: assetManifest["journey-atacama-hero"],
    cardImage: assetManifest["journey-atacama-card"],
    story: placeholderSection,
    dayRhythm: placeholderSection,
    included: placeholderSection,
    held: placeholderSection,
    fieldStatus: {
      dates: "PLACEHOLDER",
      durationDays: "DRAFT",
      capacity: "DRAFT",
      seatsRemaining: "DRAFT",
      priceLabel: "PLACEHOLDER",
      pace: "PLACEHOLDER",
      story: "PLACEHOLDER",
      dayRhythm: "PLACEHOLDER",
      included: "PLACEHOLDER",
      held: "PLACEHOLDER",
      images: "PLACEHOLDER",
    },
    demoOnly: true,
    contentStatus: "DRAFT",
    contentNote:
      "Visual-manual journey specimen only. Duration, capacity and seat label are draft; dates, price, pace, story and operating details are not supplied.",
  },
] as const satisfies readonly Journey[];

export const journeyBySlug = Object.fromEntries(
  journeys.map((journey) => [journey.slug, journey]),
) as Readonly<Record<string, Journey>>;

export const journeySlugs = journeys.map((journey) => journey.slug);
