import { rawDayRecords } from "./raw-days";
import type {
  CaravanRouteModel,
  ConditionalItemRecord,
  ContentStatus,
  ContentVisibility,
  EvidenceRecord,
  GateRecord,
  LaundryAvailabilityRecord,
  MakersEncounterRecord,
  MovementMode,
  SectionId,
  SectionRecord,
  SleepAltitudeRecord,
  StageId,
  StageRecord,
  TextRecord,
} from "./types";

const RM = "route-master-v4.2.1" as const;

function text(
  value: string,
  content_visibility: ContentVisibility = "public",
  sourceId = RM,
  status: ContentStatus = "proposed",
): TextRecord {
  return {
    text: value,
    content_visibility,
    copy_class: "locked_source",
    status,
    source_ids: [sourceId],
    recheck_date: null,
  };
}

function maker(
  strategy: MakersEncounterRecord["strategy"],
  description: string,
  status: ContentStatus = "proposed",
): MakersEncounterRecord {
  const contracted = strategy === "contracted_encounter";
  return {
    strategy,
    description,
    permission_recorded: contracted,
    payment_recorded: contracted,
    credit_recorded: contracted,
    content_visibility:
      strategy === "none_by_design" ? "internal_operations" : "public",
    status,
    source_ids: [RM],
    recheck_date: null,
  };
}

function laundry(
  availability: LaundryAvailabilityRecord["availability"],
  next_reliable_window: string | null,
  expected_turnaround: string | null = null,
): LaundryAvailabilityRecord {
  return {
    availability,
    next_reliable_window,
    expected_turnaround,
    content_visibility: "internal_operations",
    status: availability === "to_contract" ? "draft" : "proposed",
    source_ids: [RM],
    recheck_date: null,
  };
}

function stage(
  id: StageId,
  section_id: SectionId,
  name: string,
  day_start: number,
  day_end: number,
  anchor: string,
  product_behaviour: boolean,
  makers_encounter: MakersEncounterRecord,
  laundry_availability: LaundryAvailabilityRecord,
): StageRecord {
  return {
    id,
    section_id,
    name,
    day_start,
    day_end,
    anchor,
    product_behaviour,
    makers_encounter,
    laundry_availability,
    content_visibility: "public",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  };
}

function conditional(
  id: string,
  controller: string,
  fallback: string,
  notice_point: string,
  remedy: string,
): ConditionalItemRecord {
  return {
    id,
    controller,
    fallback,
    notice_point,
    remedy,
    content_visibility: "pre_sale_disclosure",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  };
}

const sleepAltitude = (
  day: number,
  metres: number | null,
  display: string | null,
  qualifier: SleepAltitudeRecord["qualifier"],
  status: ContentStatus = "proposed",
): SleepAltitudeRecord => ({
  day,
  metres,
  display,
  qualifier,
  content_visibility: "pre_sale_disclosure",
  status,
  source_ids: [RM],
  recheck_date: null,
});

export const rawGateRecords = [
  {
    id: "lima",
    name: "Lima",
    airport: "LIM",
    altitude: { metres: 0, display: "Sea level", qualifier: "sea_level" },
    gate_class: "caravan_gate",
    role: "Opens 01",
    arrival_rule: text(
      "Day 1 is protected arrival. No group visit is scheduled.",
      "pre_sale_disclosure",
    ),
    joining_load: "High - Section 01 and all through-travellers",
    leaving_load: "-",
  },
  {
    id: "cusco",
    name: "Cusco",
    airport: "CUZ",
    altitude: { metres: 3400, display: "3,400 m", qualifier: "exact" },
    gate_class: "short_form_joining_gate",
    role: "Opens the short form only",
    arrival_rule: text(
      "Previous-evening arrival and a protected orientation day. Joining only - the short form ends at Puno.",
      "pre_sale_disclosure",
    ),
    joining_load: "Moderate - short form only",
    leaving_load: "-",
  },
  {
    id: "puno",
    name: "Puno",
    airport: "JUL + road",
    altitude: { metres: 3800, display: "Approx. 3,800 m", qualifier: "approximate" },
    gate_class: "caravan_gate",
    role: "Closes 01 / opens 02",
    arrival_rule: text(
      "Through-travellers use the Day 23 arrival night. A joiner arriving from near sea level completes a Sawayatra-arranged three-night progression at Cusco (3,400 m) before transferring to Puno, subject to individual medical advice.",
      "pre_sale_disclosure",
    ),
    joining_load: "Moderate - Section 02 joiners, each on the arranged Cusco progression",
    leaving_load: "High - end of Section 01 and of the short form",
  },
  {
    id: "sucre",
    name: "Sucre",
    airport: "SRE",
    altitude: { metres: 2800, display: "Approx. 2,800 m", qualifier: "approximate" },
    gate_class: "caravan_gate",
    role: "Closes 02 / opens 03",
    arrival_rule: text(
      "Previous-evening arrival is the operating requirement; the section then provides the designed altitude progression.",
      "pre_sale_disclosure",
    ),
    joining_load: "Moderate - Section 03 joiners",
    leaving_load: "High - end of Section 02",
  },
  {
    id: "santiago",
    name: "Santiago",
    airport: "SCL",
    altitude: { metres: 520, display: "Approx. 520 m", qualifier: "approximate" },
    gate_class: "caravan_gate",
    role: "Closes 03 / opens 04",
    arrival_rule: text(
      "Last joining gate. Arrive by the previous evening for the Balmaceda flight.",
      "pre_sale_disclosure",
    ),
    joining_load: "High - all Section 04",
    leaving_load: "Moderate - end of Section 03",
  },
  {
    id: "balmaceda",
    name: "Balmaceda",
    airport: "BBA",
    altitude: { metres: 525, display: "525 m", qualifier: "exact" },
    gate_class: "caravan_gate",
    role: "Closes 04",
    arrival_rule: text(
      "Leaving gate only. The Caravan ends at the airport.",
      "pre_sale_disclosure",
    ),
    joining_load: "-",
    leaving_load: "All",
  },
] as const satisfies readonly Omit<
  GateRecord,
  "content_visibility" | "status" | "source_ids" | "recheck_date"
>[];

export const rawGates: readonly GateRecord[] = rawGateRecords.map((gate) => ({
  ...gate,
  content_visibility: "public",
  status: "proposed",
  source_ids: [RM],
  recheck_date: null,
}));

export const rawStages = [
  stage("01-a", "01", "Desert Coast", 1, 8, "stage-a", false,
    maker("required_to_contract", "Lima makers and kitchens; participation, payment, credit and image permission must be recorded."),
    laundry("to_contract", "Day 14 · Arequipa")),
  stage("01-b", "01", "White City, Deep Canyon", 9, 15, "stage-b", false,
    maker("required_to_contract", "A Colca community encounter with named local authority, agreed payment and credit."),
    laundry("available", "Day 22 · Cusco", "To be contracted at Arequipa on Day 14.")),
  stage("01-c", "01", "The Stone Road", 16, 23, "stage-c-the-stone-road", true,
    maker("required_to_contract", "A salt-pan or weaving encounter with permission, payment and credit recorded."),
    laundry("available", "Day 27 · Puno", "To be contracted at the Day 22 buffer.")),
  stage("02-a", "02", "The Islands and the Border", 24, 31, "stage-a-the-islands-and-the-border", false,
    maker("required_to_contract", "Taquile weaving and the Amantaní family stay are the stage encounters."),
    laundry("available", "Day 35 · La Paz", "To be contracted within the Day 27 buffer.")),
  stage("02-b", "02", "Thin Air and Cloud Forest", 32, 39, "stage-b", false,
    maker("required_to_contract", "A Coroico grower or maker encounter with permission, payment and credit."),
    laundry("available", "Day 40 · Sucre", "To be contracted within the Day 35 recovery day.")),
  stage("03-a", "03", "Silver and Bone", 40, 46, "stage-a", false,
    maker("required_to_contract", "A Maragua weaving encounter with named community authority, payment and credit."),
    laundry("available", "Day 54 · San Pedro de Atacama", "Last reliable window before the Salar.")),
  stage("03-b", "03", "The Salar and the Lagunas", 47, 53, "stage-b-the-salar-and-the-lagunas", false,
    maker("none_by_design", "Salt-making is in Stage A; this remote crossing has no settled-community encounter by design."),
    laundry("none", "Day 54 · San Pedro de Atacama")),
  stage("03-c", "03", "Red Earth, Open Sky", 54, 57, "stage-c", false,
    maker("required_to_contract", "Toconao or an equivalent inhabited stop carries a contracted working-community encounter."),
    laundry("available", "Section 04 operating plan", "To be contracted on Day 54.")),
  stage("04-a", "04", "Aysén and the Lake", 58, 61, "stage-a", false,
    maker("required_to_contract", "A Day 61 working household, workshop or maker encounter, with Tortel as the named fallback."),
    laundry("available", "Day 70 · Coyhaique", "To be contracted on Day 61.")),
  stage("04-b", "04", "Tortel and the Fjord", 62, 65, "stage-b", false,
    maker("none_by_design", "Tortel is read as built fabric; the section encounter belongs to Day 61, with Tortel as fallback only."),
    laundry("none", "Day 70 · Coyhaique")),
  stage("04-c", "04", "The Return and the Ferry", 66, 71, "stage-c", false,
    maker("none_by_design", "Retrace, road and water are deliberately left unprogrammed before closure."),
    laundry("available", null, "To be contracted within the Day 70 buffer.")),
] as const satisfies readonly StageRecord[];

const sectionDays = (sectionId: SectionId) =>
  rawDayRecords.filter((day) => day.section_id === sectionId);

const sectionModes = (sectionId: SectionId): readonly MovementMode[] => [
  ...new Set(sectionDays(sectionId).flatMap((day) => day.movement_modes)),
];

const sectionAltitudes = (sectionId: SectionId): readonly SleepAltitudeRecord[] =>
  sectionDays(sectionId).map((day) => day.sleep_altitude);

const stageLaundry = (stageIds: readonly StageId[]) =>
  rawStages
    .filter((record) => stageIds.includes(record.id))
    .map((record) => record.laundry_availability);

const routeMaximums = {
  "01": {
    metres_min: 4910,
    metres_max: 4910,
    display: "4,910 m at Patapampa",
    qualifier: "exact",
    survey_status: "confirmed",
    location: "Patapampa",
  },
  "02": {
    metres_min: 4115,
    metres_max: 4115,
    display: "Approx. 4,115 m at Pachatata",
    qualifier: "approximate",
    survey_status: "confirmed",
    location: "Pachatata",
  },
  "03": {
    metres_min: 4900,
    metres_max: 4980,
    display: "Approx. 4,900 to 4,980 m in the Lagunas",
    qualifier: "approximate",
    survey_status: "survey_pending",
    location: "The Lagunas",
  },
  "04": {
    metres_min: 1120,
    metres_max: 1120,
    display: "Approx. 1,120 m · route survey to confirm",
    qualifier: "approximate",
    survey_status: "survey_pending",
    location: "Section 04 route high point",
  },
} as const;

const withRecord = <T extends object>(value: T) => ({
  ...value,
  content_visibility: "pre_sale_disclosure" as const,
  status: "proposed" as const,
  source_ids: [RM] as const,
  recheck_date: null,
});

const gateLoad = (value: string) => text(value, "internal_operations");
const joinRule = (value: string) => text(value, "pre_sale_disclosure");
const internal = (value: string) => text(value, "internal_operations");
const legal = (value: string) => text(value, "legal_review", RM, "draft");

export const rawSections = [
  {
    section_id: "01",
    name: "Sea to Stone",
    subline: null,
    day_start: 1,
    day_end: 23,
    stages: ["01-a", "01-b", "01-c"],
    short_form_exception: {
      id: "the-stone-road",
      name: "The Stone Road",
      stage_id: "01-c",
      day_start: 16,
      day_end: 23,
      gate_from: "cusco",
      gate_to: "puno",
      shared_inventory: true,
      inventory_additive: false,
      closed_to_other_stages: true,
      canonical_for: "/journeys/caravans/andean-caravan/sea-to-stone",
      canonical_document_has_fragment: false,
      legacy_url: ["/departures/the-stone-road"],
      content_visibility: "public",
      status: "proposed",
      source_ids: [RM],
      recheck_date: null,
    },
    gate_from: "lima",
    gate_to: "puno",
    gate_load: gateLoad("Lima high joining load; Puno high leaving load and moderate onward joining load."),
    join_rule: joinRule("Day 1 is a protected arrival. The Stone Road requires previous-evening arrival in Cusco; morning-of-Day-16 arrival is not permitted."),
    pre_section_progression: null,
    acclimatisation_ladder: rawDayRecords.slice(0, 23).map((day) => day.sleep_altitude),
    group_max: 12,
    min_operating_number: {
      value: null, assessment_date: null, content_visibility: "internal_operations",
      status: "draft", source_ids: [RM], recheck_date: null,
    },
    route_max_altitude: withRecord(routeMaximums["01"]),
    sleep_altitudes: sectionAltitudes("01"),
    movement_modes: sectionModes("01"),
    movement_time_basis: "Road time, scheduled travel and total elapsed movement are distinct per day record.",
    season_public: text("February 2028 · coastal summer, Andean wet season"),
    declared_load_exception: null,
    makers_encounter: maker("required_to_contract", "At least one substantive maker, household, workshop or community encounter in each stage."),
    laundry_availability: stageLaundry(["01-a", "01-b", "01-c"]),
    exit_points: ["Arequipa", "Cusco"],
    steward_continuity: internal("A named Deputy Steward, stage handovers, rest and relief remain to be contracted."),
    sleep_standard: text("One Caravan standard, with explicit remote exceptions after inspection.", "pre_sale_disclosure"),
    demands: [
      text("Long road days, exposed archaeological ground, a 4,910 m pass, wet stone and a full-day train.", "pre_sale_disclosure"),
    ],
    conditional_items: [
      conditional("s01-ballestas", "Harbour clearance and sea state", "The reserve becomes the primary landscape day", "Before enquiry", "No boat departure is guaranteed"),
      conditional("s01-machu-picchu", "2028 permits and route rules", "Complementary routes under the rules then in force", "Before exact circuits are named", "No circuit, time or viewpoint is guaranteed before purchase"),
    ],
    gate_social_protocol: internal("Arrival, introduction, departure, welfare handover and unresolved-issue ownership are assigned at Lima, Cusco and Puno."),
    conduct_policy: legal("[SIGN-OFF] Conduct, removal authority, exit procedure and financial consequence require legal approval."),
    transport_standard: internal("PRODUCTION NOTE: vehicle inspection, belts, driver hours, comfort intervals, no planned night driving, backup and luggage capacity are required."),
    canonical_for: "/journeys/caravans/andean-caravan/sea-to-stone",
    legacy_url: ["/departures/desert-coast", "/departures/white-city-deep-canyon"],
    cta: text("Ask about Sea to Stone - 23 days from Lima to Puno - or about The Stone Road, eight days from Cusco to Puno. No payment is taken through the website."),
    content_visibility: "public",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  },
  {
    section_id: "02",
    name: "Both Shores",
    subline: "Titicaca, La Paz and the cloud forest",
    day_start: 24,
    day_end: 39,
    stages: ["02-a", "02-b"],
    short_form_exception: null,
    gate_from: "puno",
    gate_to: "sucre",
    gate_load: gateLoad("Puno moderate joining and departure-hub load; Sucre high leaving and moderate joining load."),
    join_rule: joinRule("A joiner arriving from near sea level completes a Sawayatra-arranged three-night progression at Cusco before transfer to Puno. Payment does not establish readiness."),
    pre_section_progression: {
      location: "Cusco",
      nights: 3,
      sleeping_altitudes: [
        sleepAltitude(-3, 3400, "3,400 m · Cusco · night 1", "exact"),
        sleepAltitude(-2, 3400, "3,400 m · Cusco · night 2", "exact"),
        sleepAltitude(-1, 3400, "3,400 m · Cusco · night 3", "exact"),
      ],
      transfer: "Arranged road transfer from Cusco to Puno before Day 24",
      cost: null,
      inclusion_status: "pending",
      required: true,
      content_visibility: "pre_sale_disclosure",
      status: "proposed",
      source_ids: [RM],
      recheck_date: null,
    },
    acclimatisation_ladder: [
      sleepAltitude(-3, 3400, "Cusco progression · night 1 · 3,400 m", "exact"),
      sleepAltitude(-2, 3400, "Cusco progression · night 2 · 3,400 m", "exact"),
      sleepAltitude(-1, 3400, "Cusco progression · night 3 · 3,400 m", "exact"),
      ...rawDayRecords.slice(23, 26).map((day) => day.sleep_altitude),
    ],
    group_max: 12,
    min_operating_number: {
      value: null, assessment_date: null, content_visibility: "internal_operations",
      status: "draft", source_ids: [RM], recheck_date: null,
    },
    route_max_altitude: withRecord(routeMaximums["02"]),
    sleep_altitudes: sectionAltitudes("02"),
    movement_modes: sectionModes("02"),
    movement_time_basis: "Boat, road, border and scheduled-flight records declare their own basis.",
    season_public: text("Late February to mid-March 2028 · wet season"),
    declared_load_exception: null,
    makers_encounter: maker("required_to_contract", "Island-community, family-stay and Yungas grower encounters require permission, payment and credit."),
    laundry_availability: stageLaundry(["02-a", "02-b"]),
    exit_points: ["La Paz"],
    steward_continuity: internal("A named Deputy Steward, gate handovers, rest and relief remain to be contracted."),
    sleep_standard: text("One Caravan standard; the Amantaní family house is an explicit local-supply exception.", "pre_sale_disclosure"),
    demands: [
      text("High sleeping altitudes, small passenger boats, steep island paths and an international land border.", "pre_sale_disclosure"),
    ],
    conditional_items: [
      conditional("s02-lake", "Wind, swell and community operating conditions", "Day 27 recovers displaced island time where possible", "Before enquiry", "Day 27 remains a protected buffer and is not resold"),
      conditional("s02-yungas", "Wet-season road status", "A closure alternative is used; no driving after dark", "Before the Coroico movement", "The modern road is used, never the Death Road"),
    ],
    gate_social_protocol: internal("Puno and Sucre handovers assign introduction, welfare and unresolved-issue ownership."),
    conduct_policy: legal("[SIGN-OFF] Conduct, removal authority, border exit procedure and financial consequence require legal approval."),
    transport_standard: internal("PRODUCTION NOTE: inspect boats, contract cross-border luggage movement and prohibit planned night driving."),
    canonical_for: "/journeys/caravans/andean-caravan/both-shores",
    legacy_url: ["/departures/both-shores", "/departures/thin-air-cloud-forest"],
    cta: text("Ask about Both Shores - 16 days from Puno to Sucre - or about continuing into The Mirror."),
    content_visibility: "public",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  },
  {
    section_id: "03",
    name: "The Mirror",
    subline: null,
    day_start: 40,
    day_end: 57,
    stages: ["03-a", "03-b", "03-c"],
    short_form_exception: null,
    gate_from: "sucre",
    gate_to: "santiago",
    gate_load: gateLoad("Sucre moderate joining and high leaving load; Santiago high joining and moderate leaving load."),
    join_rule: joinRule("Previous-evening arrival in Sucre at approximately 2,800 m is required. No arranged pre-section progression is needed."),
    pre_section_progression: null,
    acclimatisation_ladder: rawDayRecords.slice(38, 49).map((day) => day.sleep_altitude),
    group_max: 12,
    min_operating_number: {
      value: null, assessment_date: null, content_visibility: "internal_operations",
      status: "draft", source_ids: [RM], recheck_date: null,
    },
    route_max_altitude: withRecord(routeMaximums["03"]),
    sleep_altitudes: sectionAltitudes("03"),
    movement_modes: sectionModes("03"),
    movement_time_basis: "Road, 4×4, border and scheduled-flight records declare their own basis.",
    season_public: text("Mid to late March 2028 · wet season, wet-season mirror"),
    declared_load_exception: {
      name: "Declared Load Exception",
      day_start: 49,
      day_end: 53,
      disclosure: text("Five consecutive Demanding days. Two long 4×4 days, three refuge nights between approximately 4,100 and 4,600 m with shared bathrooms and limited heating, and a pre-dawn border day reaching the route’s highest point at approximately 4,900 to 4,980 m.", "pre_sale_disclosure"),
      structural_reason: text("There is no road, no service and no property between them that could hold a recovery day. The alternative is not a gentler crossing; it is no crossing.", "pre_sale_disclosure"),
      protected_shoulders: [48, 54],
      consecutive_demanding_days: 5,
      refuge_nights: 3,
      sleep_altitude_range: "Approx. 4,100–4,600 m",
      content_visibility: "pre_sale_disclosure",
      status: "proposed",
      source_ids: [RM],
      recheck_date: null,
    },
    makers_encounter: maker("required_to_contract", "Maragua and the Atacama each require a substantive encounter; the remote Lagunas stage is none_by_design."),
    laundry_availability: stageLaundry(["03-a", "03-b", "03-c"]),
    exit_points: ["Uyuni", "Calama"],
    steward_continuity: internal("The Section 03 Host requires documented Deputy Steward qualification and a written handover plan."),
    sleep_standard: text("Three refuge nights use one explicit remote standard with shared bathrooms and limited heating.", "pre_sale_disclosure"),
    demands: [
      text("Five consecutive Demanding days, rough track, cold, wind, three refuge nights and a pre-dawn border day.", "pre_sale_disclosure"),
    ],
    conditional_items: [
      conditional("s03-salar", "Water, crust and the contracted operator", "The line uses edge tracks or other usable salt access", "Before enquiry and again at Day 46", "Two days are allotted to the Salar; a flooded crossing is not guaranteed"),
      conditional("s03-border", "2028 border hours and Chilean entry controls", "The crossing follows the contracted delay and withdrawal plan", "Before the remote crossing", "A Day 46 withdrawal route must be supplied before sale"),
    ],
    gate_social_protocol: internal("Sucre and Santiago handovers assign arrival, introduction, departure and welfare ownership."),
    conduct_policy: legal("[SIGN-OFF] Conduct, medical withdrawal, removal authority and financial consequence require legal approval."),
    transport_standard: internal("OPERATING TARGET: three guest 4×4s for twelve travellers plus separate guide and support capacity, with every seat assigned."),
    canonical_for: "/journeys/caravans/andean-caravan/the-mirror",
    legacy_url: ["/departures/silver-and-bone", "/departures/the-mirror", "/departures/atacama"],
    cta: text("Ask about The Mirror - 18 days from Sucre to Santiago - after reading the Declared Load Exception, refuge, altitude and cold disclosures. This section is remote by design."),
    content_visibility: "public",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  },
  {
    section_id: "04",
    name: "The End of the Road",
    subline: null,
    day_start: 58,
    day_end: 71,
    stages: ["04-a", "04-b", "04-c"],
    short_form_exception: null,
    gate_from: "santiago",
    gate_to: "balmaceda",
    gate_load: gateLoad("Santiago high joining load; Balmaceda is leaving-only for all travellers."),
    join_rule: joinRule("Arrive in Santiago by the previous evening for the scheduled Balmaceda flight. Balmaceda is a leaving gate only."),
    pre_section_progression: null,
    acclimatisation_ladder: [],
    group_max: 12,
    min_operating_number: {
      value: null, assessment_date: null, content_visibility: "internal_operations",
      status: "draft", source_ids: [RM], recheck_date: null,
    },
    route_max_altitude: withRecord(routeMaximums["04"]),
    sleep_altitudes: sectionAltitudes("04"),
    movement_modes: sectionModes("04"),
    movement_time_basis: "Flight, road, ferry and vessel records declare scheduled travel or total elapsed movement separately.",
    season_public: text("Late March to mid-April 2028 · Patagonian autumn"),
    declared_load_exception: null,
    makers_encounter: maker("required_to_contract", "A Day 61 household, workshop or maker encounter is required, with Tortel as the named fallback."),
    laundry_availability: stageLaundry(["04-a", "04-b", "04-c"]),
    exit_points: ["Coyhaique"],
    steward_continuity: internal("Through-Journey Steward responsibility continues through the agreed Balmaceda airport handover."),
    sleep_standard: text("Remote local supply is inspected for warmth, bathroom access and luggage route; no decorative tier labels are inferred.", "pre_sale_disclosure"),
    demands: [
      text("Ripio, long seated days, vehicle ferries, weather-dependent small vessels and Tortel boardwalks and stairs.", "pre_sale_disclosure"),
    ],
    conditional_items: [
      conditional("s04-marble-chapels", "Wind and the contracted vessel operator", "Morning and afternoon remain available for the safer window", "Before enquiry", "A written cancellation outcome is supplied"),
      conditional("s04-ohiggins", "Wind, lake conditions and the contracted vessel operator", "Day 65 is the protected second window; otherwise a local day", "Before enquiry", "The agreed refund or credit applies if neither window operates"),
    ],
    gate_social_protocol: internal("Santiago introduction and Balmaceda airport handover have named welfare and unresolved-issue owners."),
    conduct_policy: legal("[SIGN-OFF] Conduct, remote removal, ferry disruption and extra-night terms require legal approval."),
    transport_standard: internal("PRODUCTION NOTE: inspect vessels, prohibit planned driving after dark and carry satellite communication south of Cochrane."),
    canonical_for: "/journeys/caravans/andean-caravan/the-end-of-the-road",
    legacy_url: ["/departures/the-end-of-the-road"],
    cta: text("Ask about The End of the Road - 14 days from Santiago to Balmaceda - after reading the ferry, small-vessel, Tortel and weather disclosures. Balmaceda is a leaving gate only."),
    content_visibility: "public",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  },
] as const satisfies readonly SectionRecord[];

export const rawEvidence = [
  {
    source_id: RM,
    claim_supported: "Canonical 71-day route, four-section product structure and Section 11 content schema",
    source_owner: "Sawayatra",
    url_or_document: "Sawayatra-01-Andean-Caravan-Route-Master-v4_2_1-LOCKED.docx",
    date_accessed: "2026-08-10",
    evidence_excerpt: "Locked route and content system audited for Phase 2.",
    rechecked_by: null,
    replacement_source: null,
    content_visibility: "internal_operations",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  },
  {
    source_id: "nasa-santiago-elevation",
    claim_supported: "Santiago elevation is approximately 520 m",
    source_owner: "NASA Earth Observatory",
    url_or_document: "Route Master verification ledger reference",
    date_accessed: null,
    evidence_excerpt: "Source migration into a dated evidence record remains required before secured status.",
    rechecked_by: null,
    replacement_source: null,
    content_visibility: "internal_operations",
    status: "draft",
    source_ids: [RM],
    recheck_date: null,
  },
  {
    source_id: "chile-dgac-balmaceda-elevation",
    claim_supported: "Balmaceda Airport elevation is 525 m",
    source_owner: "Chile DGAC",
    url_or_document: "Route Master verification ledger reference",
    date_accessed: null,
    evidence_excerpt: "Source migration into a dated evidence record remains required before secured status.",
    rechecked_by: null,
    replacement_source: null,
    content_visibility: "internal_operations",
    status: "draft",
    source_ids: [RM],
    recheck_date: null,
  },
] as const satisfies readonly EvidenceRecord[];

export const rawAndeanCaravanModel: CaravanRouteModel = {
  id: "andean-caravan",
  name: "The Andean Caravan",
  content_visibility: "public",
  status: "proposed",
  source_ids: [RM],
  recheck_date: null,
  day_start: 1,
  day_end: 71,
  duration_days: 71,
  group_max: 12,
  scheduled_flight_movements_total: 5,
  scheduled_flight_movements_in_route: 4,
  gates: rawGates,
  stages: rawStages,
  sections: rawSections,
  days: rawDayRecords,
  included_exit_movement: {
    from: "balmaceda",
    to: "santiago",
    mode: "scheduled flight",
    included: true,
    outside_route_geometry: true,
    content_visibility: "pre_sale_disclosure",
    status: "proposed",
    source_ids: [RM],
    recheck_date: null,
  },
  evidence: rawEvidence,
};
