export type FamilyKey =
  | "LLLL" | "LLLR" | "LRLL" | "LRLR"
  | "LLRL" | "LLRR" | "LRRL" | "LRRR"
  | "RLLL" | "RLLR" | "RRLL" | "RRLR"
  | "RLRL" | "RLRR" | "RRRL" | "RRRR";

export interface TravelFamily {
  readonly key: FamilyKey;
  readonly name: string;
  readonly readout: string;
  readonly essence: string;
  readonly whatYouBring: string;
}

export const FAMILIES: Readonly<Record<FamilyKey, TravelFamily>> = {
  LLLL: { key: "LLLL", name: "The Seeker", readout: "unhurried · unplanned · quiet · dawn-led", essence: "You are up before the town is, and you do not yet know where you are going. That is the point. A day settled in advance feels to you like a day already spent, and the hours that stay with you are the ones you walked into without knowing.", whatYouBring: "the discovery nobody booked." },
  LLLR: { key: "LLLR", name: "The Drifter", readout: "unhurried · unplanned · quiet · night-led", essence: "You let the evening decide. You are unhurried, unscheduled and content in your own company, and you have never once regretted staying out an hour longer than was sensible. Where a day is going matters less to you than what it turns out to be.", whatYouBring: "an ease with not knowing yet." },
  LRLL: { key: "LRLL", name: "The Naturalist", readout: "unhurried · charted · quiet · dawn-led", essence: "You want the day to have a shape and the shape to start early. You have read about where you are going, you know what you hope to see, and you would rather wait two hours in one place than pass through four. Patience is your method, not a virtue you are performing.", whatYouBring: "preparation, and the stillness to use it." },
  LRLR: { key: "LRLR", name: "The Astronomer", readout: "unhurried · charted · quiet · night-led", essence: "You like a journey with room around it — enough structure to trust the road, enough quiet to notice where it has taken you. You do not need to lead the group or fill its silences, but you need the day to have a plan and the evening to stay open.", whatYouBring: "steadiness, and attention to what everyone else walked past." },
  LLRL: { key: "LLRL", name: "The Regular", readout: "unhurried · unplanned · sociable · dawn-led", essence: "By the third morning the café knows your order. You did not plan that and you could not repeat it on purpose — you simply go slowly, turn up early, and talk to whoever is there. You come home with people rather than photographs.", whatYouBring: "a place that has started to know the group." },
  LLRR: { key: "LLRR", name: "The Bohemian", readout: "unhurried · unplanned · sociable · night-led", essence: "The table is the destination. You are in no hurry, you have made no plan, and you assume the evening will produce whatever it produces — which, in your experience, it reliably does. A long dinner is not a break from the journey. It is the journey.", whatYouBring: "the night everyone talks about afterwards." },
  LRRL: { key: "LRRL", name: "The Host", readout: "unhurried · charted · sociable · dawn-led", essence: "You have thought about the day and you have thought about the people. Breakfast is where you gather them — unhurried, with a plan you are perfectly happy to be talked out of. You are organising, but nobody feels organised.", whatYouBring: "a group that has eaten and knows the day by nine." },
  LRRR: { key: "LRRR", name: "The Convener", readout: "unhurried · charted · sociable · night-led", essence: "You booked the table three days ago. Slow days, a long evening, everyone in one place at the end of it — that is a journey well spent, and you are willing to do the arranging that makes it happen rather than hoping it will.", whatYouBring: "the evening that would not have happened by itself." },
  RLLL: { key: "RLLL", name: "The Scout", readout: "full-tilt · unplanned · quiet · dawn-led", essence: "You are ahead, early, and working it out as you go. You would rather cover ground and adjust than settle a plan you may want to abandon by ten. You do not need company for this, though you will happily come back and report what is up there.", whatYouBring: "the road ahead, checked before anyone else is awake." },
  RLLR: { key: "RLLR", name: "The Nomad", readout: "full-tilt · unplanned · quiet · night-led", essence: "You move fast and late and you do not much mind where you sleep. Plans feel like weight. You have crossed three towns in a day on no notice and thought nothing of it, and you are more comfortable than most people with not knowing about tomorrow.", whatYouBring: "the willingness to go now." },
  RRLL: { key: "RRLL", name: "The Pathfinder", readout: "full-tilt · charted · quiet · dawn-led", essence: "You know the route, the timings and where the difficulty is, and you would like to start early enough to get through it. You are not being rigid. You have simply found that a fast day only works when somebody has thought it through first.", whatYouBring: "a hard day that goes right." },
  RRLR: { key: "RRLR", name: "The Navigator", readout: "full-tilt · charted · quiet · night-led", essence: "You plan precisely, move quickly and keep your own counsel. The others discover on the second evening that you knew about the ferry, the closure and the shortcut, and had said nothing about any of it because nobody asked.", whatYouBring: "the problem that was solved before it arrived." },
  RLRL: { key: "RLRL", name: "The Bugler", readout: "full-tilt · unplanned · sociable · dawn-led", essence: "At six in the morning you are certain everyone would be happier awake, and often you are right. You have no plan — you have energy, and a conviction that the day is better started than discussed. People follow you before they have decided to.", whatYouBring: "momentum, at the hour when it is hardest to find." },
  RLRR: { key: "RLRR", name: "The Catalyst", readout: "full-tilt · unplanned · sociable · night-led", essence: "Nothing was going to happen tonight until you suggested it. You move fast, you make no plans, and you are the reason a quiet evening becomes the one people describe when they get home. You do not organise. You start.", whatYouBring: "the evening that turned." },
  RRRL: { key: "RRRL", name: "The Conductor", readout: "full-tilt · charted · sociable · dawn-led", essence: "You set the tempo and you gather the people, and you are up early doing both. The day has a shape, everyone knows it, and it moves. You take real pleasure in a group that is running well and none at all in one that is drifting.", whatYouBring: "a full day that still ends on time." },
  RRRR: { key: "RRRR", name: "The Ringmaster", readout: "full-tilt · charted · sociable · night-led", essence: "You want all of it and you have arranged all of it — the fast day, the full table, the late night. You are the one who booked the thing at eleven and got everybody there. Sleep, to you, is a scheduling matter.", whatYouBring: "more journey per day than anyone thought possible." },
};

export const FAMILY_KEYS = Object.keys(FAMILIES) as FamilyKey[];
export const FAMILY_LIST = FAMILY_KEYS.map((key) => FAMILIES[key]);
